// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmYcjuAzRbjsY7HRo56VsE6nr99rYnL1c',
    appId: '1:473405547044:web:88213b4dcf825d3f2c2eb1',
    messagingSenderId: '473405547044',
    projectId: 'atelier4-a-aboufaresse-i-de46d',
    authDomain: 'atelier4-a-aboufaresse-i-de46d.firebaseapp.com',
    storageBucket: 'atelier4-a-aboufaresse-i-de46d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk6TrT_jxAOjZj0iZP4Vi1c5tOBzwpCiE',
    appId: '1:473405547044:android:8e17c52b0e37d95c2c2eb1',
    messagingSenderId: '473405547044',
    projectId: 'atelier4-a-aboufaresse-i-de46d',
    storageBucket: 'atelier4-a-aboufaresse-i-de46d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUAoTEaVmi8lL3Bnl1zRj7C2Rr55hLDfo',
    appId: '1:473405547044:ios:89d84e29c446938e2c2eb1',
    messagingSenderId: '473405547044',
    projectId: 'atelier4-a-aboufaresse-i-de46d',
    storageBucket: 'atelier4-a-aboufaresse-i-de46d.firebasestorage.app',
    iosBundleId: 'com.example.atelier4AAboufaresseIirg6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUAoTEaVmi8lL3Bnl1zRj7C2Rr55hLDfo',
    appId: '1:473405547044:ios:89d84e29c446938e2c2eb1',
    messagingSenderId: '473405547044',
    projectId: 'atelier4-a-aboufaresse-i-de46d',
    storageBucket: 'atelier4-a-aboufaresse-i-de46d.firebasestorage.app',
    iosBundleId: 'com.example.atelier4AAboufaresseIirg6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmYcjuAzRbjsY7HRo56VsE6nr99rYnL1c',
    appId: '1:473405547044:web:01af29ec8e5811ab2c2eb1',
    messagingSenderId: '473405547044',
    projectId: 'atelier4-a-aboufaresse-i-de46d',
    authDomain: 'atelier4-a-aboufaresse-i-de46d.firebaseapp.com',
    storageBucket: 'atelier4-a-aboufaresse-i-de46d.firebasestorage.app',
  );
}
